/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mapa.view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import mapa.core.dao.UserDao;
import mapa.core.entity.User;

/**
 *
 * @author Marcos Almeida - https://github.com/MarcosGruah
 */
public class LoginView extends javax.swing.JFrame {

    /**
     * Creates new form LoginView
     */
    public LoginView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundJPanel = new javax.swing.JPanel();
        cardLayoutJPanel = new javax.swing.JPanel();
        loginJPanel = new javax.swing.JPanel();
        logoComponentsJPanel = new javax.swing.JPanel();
        companyNameJLabel = new javax.swing.JLabel();
        companyLogoIconJLabel = new javax.swing.JLabel();
        loginComponentsJPanel = new javax.swing.JPanel();
        loginIconJLabel = new javax.swing.JLabel();
        loginJTextField = new javax.swing.JTextField();
        loginJSeparator = new javax.swing.JSeparator();
        passwordIconJLabel = new javax.swing.JLabel();
        passwordJPasswordField = new javax.swing.JPasswordField();
        passwordJSeparator = new javax.swing.JSeparator();
        buttonComponentsPanel = new javax.swing.JPanel();
        registerJButton = new javax.swing.JButton();
        loginJButton = new javax.swing.JButton();
        registerJPanel = new javax.swing.JPanel();
        headerComponentsJPanel = new javax.swing.JPanel();
        registerTitleJLabel = new javax.swing.JLabel();
        registerComponentsJPanel = new javax.swing.JPanel();
        nameRegisterJTextField = new javax.swing.JTextField();
        nameRegisterJSeparator = new javax.swing.JSeparator();
        loginRegisterJTextField = new javax.swing.JTextField();
        loginRegisterJSeparator = new javax.swing.JSeparator();
        passwordRegisterJPasswordField = new javax.swing.JPasswordField();
        passwordRegisterJSeparator = new javax.swing.JSeparator();
        emailRegisterJTextField = new javax.swing.JTextField();
        emailRegisterJSeparator = new javax.swing.JSeparator();
        returnRegisterJButton = new javax.swing.JButton();
        newUserRegisterJButton = new javax.swing.JButton();
        loaderJPanel = new javax.swing.JPanel();
        loadingIconJLabel = new javax.swing.JLabel();
        loadingTextJLabel = new javax.swing.JLabel();
        loginSucessJPanel = new javax.swing.JPanel();
        loginSucessbgJPanel = new javax.swing.JPanel();
        companyLogoSuccessIconJLabel = new javax.swing.JLabel();
        loginSuccessTextJLabel = new javax.swing.JLabel();
        returnSucessJButton = new javax.swing.JButton();
        loginFailJPanel = new javax.swing.JPanel();
        loginFailbgJPanel = new javax.swing.JPanel();
        companyLogoFailIconJLabel = new javax.swing.JLabel();
        loginFailTextJLabel1 = new javax.swing.JLabel();
        loginFailTextJLabel2 = new javax.swing.JLabel();
        loginFailTextJLabel3 = new javax.swing.JLabel();
        returnFailJButton = new javax.swing.JButton();
        newRegisterFailLoginButton = new javax.swing.JButton();
        registerSucessJPanel = new javax.swing.JPanel();
        registerSucessbgJPanel = new javax.swing.JPanel();
        companyLogoSuccessIconJLabel1 = new javax.swing.JLabel();
        registerSucessTextJLabel = new javax.swing.JLabel();
        returnRegSucessJButton1 = new javax.swing.JButton();
        footerJLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Login");
        setResizable(false);

        backgroundJPanel.setBackground(new java.awt.Color(227, 231, 242));
        backgroundJPanel.setMinimumSize(new java.awt.Dimension(800, 500));
        backgroundJPanel.setPreferredSize(new java.awt.Dimension(800, 500));

        cardLayoutJPanel.setBackground(new java.awt.Color(255, 255, 255));
        cardLayoutJPanel.setMinimumSize(new java.awt.Dimension(800, 470));
        cardLayoutJPanel.setPreferredSize(new java.awt.Dimension(800, 470));
        cardLayoutJPanel.setLayout(new java.awt.CardLayout());

        loginJPanel.setBackground(new java.awt.Color(255, 255, 255));
        loginJPanel.setMinimumSize(new java.awt.Dimension(800, 470));
        loginJPanel.setPreferredSize(new java.awt.Dimension(800, 470));

        logoComponentsJPanel.setBackground(new java.awt.Color(255, 255, 255));
        logoComponentsJPanel.setMinimumSize(new java.awt.Dimension(350, 220));
        logoComponentsJPanel.setPreferredSize(new java.awt.Dimension(350, 220));

        companyNameJLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        companyNameJLabel.setForeground(new java.awt.Color(0, 80, 204));
        companyNameJLabel.setText("Sistema de Login");
        companyNameJLabel.setFocusable(false);
        companyNameJLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        companyLogoIconJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        companyLogoIconJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mapa/assets/logo.png"))); // NOI18N

        javax.swing.GroupLayout logoComponentsJPanelLayout = new javax.swing.GroupLayout(logoComponentsJPanel);
        logoComponentsJPanel.setLayout(logoComponentsJPanelLayout);
        logoComponentsJPanelLayout.setHorizontalGroup(
            logoComponentsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoComponentsJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(logoComponentsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(companyLogoIconJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoComponentsJPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(companyNameJLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        logoComponentsJPanelLayout.setVerticalGroup(
            logoComponentsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoComponentsJPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(companyNameJLabel)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(companyLogoIconJLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        loginComponentsJPanel.setBackground(new java.awt.Color(255, 255, 255));
        loginComponentsJPanel.setMinimumSize(new java.awt.Dimension(350, 135));
        loginComponentsJPanel.setPreferredSize(new java.awt.Dimension(350, 135));

        loginIconJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mapa/assets/user.png"))); // NOI18N

        loginJTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        loginJTextField.setText("Login");
        loginJTextField.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 5)));
        loginJTextField.setMargin(new java.awt.Insets(2, 2, 2, 2));
        loginJTextField.setMinimumSize(new java.awt.Dimension(200, 24));
        loginJTextField.setPreferredSize(new java.awt.Dimension(200, 24));
        loginJTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                loginJTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                loginJTextFieldFocusLost(evt);
            }
        });

        loginJSeparator.setBackground(new java.awt.Color(66, 141, 255));
        loginJSeparator.setForeground(new java.awt.Color(66, 141, 255));
        loginJSeparator.setOpaque(true);
        loginJSeparator.setPreferredSize(new java.awt.Dimension(200, 2));

        passwordIconJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mapa/assets/padlock.png"))); // NOI18N

        passwordJPasswordField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        passwordJPasswordField.setText("Senha");
        passwordJPasswordField.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 5)));
        passwordJPasswordField.setEchoChar((char)0);
        passwordJPasswordField.setMargin(new java.awt.Insets(2, 2, 2, 2));
        passwordJPasswordField.setMinimumSize(new java.awt.Dimension(200, 24));
        passwordJPasswordField.setPreferredSize(new java.awt.Dimension(200, 24));
        passwordJPasswordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordJPasswordFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordJPasswordFieldFocusLost(evt);
            }
        });

        passwordJSeparator.setBackground(new java.awt.Color(66, 141, 255));
        passwordJSeparator.setForeground(new java.awt.Color(66, 141, 255));
        passwordJSeparator.setOpaque(true);
        passwordJSeparator.setPreferredSize(new java.awt.Dimension(200, 2));

        javax.swing.GroupLayout loginComponentsJPanelLayout = new javax.swing.GroupLayout(loginComponentsJPanel);
        loginComponentsJPanel.setLayout(loginComponentsJPanelLayout);
        loginComponentsJPanelLayout.setHorizontalGroup(
            loginComponentsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginComponentsJPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(loginComponentsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loginIconJLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordIconJLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(loginComponentsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(loginJTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(loginJSeparator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(passwordJSeparator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(passwordJPasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        loginComponentsJPanelLayout.setVerticalGroup(
            loginComponentsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginComponentsJPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(loginComponentsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(loginComponentsJPanelLayout.createSequentialGroup()
                        .addComponent(loginJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(loginJSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(loginIconJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(loginComponentsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(loginComponentsJPanelLayout.createSequentialGroup()
                        .addComponent(passwordJPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(passwordJSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(passwordIconJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        buttonComponentsPanel.setBackground(new java.awt.Color(255, 255, 255));
        buttonComponentsPanel.setPreferredSize(new java.awt.Dimension(495, 24));

        registerJButton.setBackground(new java.awt.Color(66, 141, 255));
        registerJButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        registerJButton.setForeground(new java.awt.Color(255, 255, 255));
        registerJButton.setText("Criar Conta");
        registerJButton.setFocusable(false);
        registerJButton.setPreferredSize(new java.awt.Dimension(90, 24));
        registerJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerJButtonActionPerformed(evt);
            }
        });

        loginJButton.setBackground(new java.awt.Color(66, 141, 255));
        loginJButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        loginJButton.setForeground(new java.awt.Color(255, 255, 255));
        loginJButton.setText("Entrar");
        loginJButton.setFocusable(false);
        loginJButton.setPreferredSize(new java.awt.Dimension(90, 24));
        loginJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonComponentsPanelLayout = new javax.swing.GroupLayout(buttonComponentsPanel);
        buttonComponentsPanel.setLayout(buttonComponentsPanelLayout);
        buttonComponentsPanelLayout.setHorizontalGroup(
            buttonComponentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonComponentsPanelLayout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(registerJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(loginJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(133, Short.MAX_VALUE))
        );
        buttonComponentsPanelLayout.setVerticalGroup(
            buttonComponentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonComponentsPanelLayout.createSequentialGroup()
                .addGroup(buttonComponentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerJButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginJButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout loginJPanelLayout = new javax.swing.GroupLayout(loginJPanel);
        loginJPanel.setLayout(loginJPanelLayout);
        loginJPanelLayout.setHorizontalGroup(
            loginJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginJPanelLayout.createSequentialGroup()
                .addContainerGap(153, Short.MAX_VALUE)
                .addGroup(loginJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(logoComponentsJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE)
                    .addComponent(loginComponentsJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE)
                    .addComponent(buttonComponentsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        loginJPanelLayout.setVerticalGroup(
            loginJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginJPanelLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(logoComponentsJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginComponentsJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(buttonComponentsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        cardLayoutJPanel.add(loginJPanel, "card2");

        registerJPanel.setBackground(new java.awt.Color(255, 255, 255));
        registerJPanel.setMinimumSize(new java.awt.Dimension(800, 470));
        registerJPanel.setPreferredSize(new java.awt.Dimension(800, 470));

        headerComponentsJPanel.setBackground(new java.awt.Color(255, 255, 255));
        headerComponentsJPanel.setMinimumSize(new java.awt.Dimension(350, 220));

        registerTitleJLabel.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        registerTitleJLabel.setForeground(new java.awt.Color(66, 141, 255));
        registerTitleJLabel.setText("Cadastro");
        registerTitleJLabel.setFocusable(false);
        registerTitleJLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout headerComponentsJPanelLayout = new javax.swing.GroupLayout(headerComponentsJPanel);
        headerComponentsJPanel.setLayout(headerComponentsJPanelLayout);
        headerComponentsJPanelLayout.setHorizontalGroup(
            headerComponentsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerComponentsJPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(registerTitleJLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerComponentsJPanelLayout.setVerticalGroup(
            headerComponentsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerComponentsJPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(registerTitleJLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        registerComponentsJPanel.setBackground(new java.awt.Color(255, 255, 255));
        registerComponentsJPanel.setMinimumSize(new java.awt.Dimension(350, 135));

        nameRegisterJTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nameRegisterJTextField.setText("Nome");
        nameRegisterJTextField.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 5)));
        nameRegisterJTextField.setMargin(new java.awt.Insets(2, 2, 2, 2));
        nameRegisterJTextField.setPreferredSize(new java.awt.Dimension(200, 24));
        nameRegisterJTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameRegisterJTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameRegisterJTextFieldFocusLost(evt);
            }
        });

        nameRegisterJSeparator.setBackground(new java.awt.Color(66, 141, 255));
        nameRegisterJSeparator.setForeground(new java.awt.Color(66, 141, 255));
        nameRegisterJSeparator.setOpaque(true);
        nameRegisterJSeparator.setPreferredSize(new java.awt.Dimension(200, 2));

        loginRegisterJTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        loginRegisterJTextField.setText("Login");
        loginRegisterJTextField.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 5)));
        loginRegisterJTextField.setMargin(new java.awt.Insets(2, 2, 2, 2));
        loginRegisterJTextField.setPreferredSize(new java.awt.Dimension(200, 24));
        loginRegisterJTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                loginRegisterJTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                loginRegisterJTextFieldFocusLost(evt);
            }
        });

        loginRegisterJSeparator.setBackground(new java.awt.Color(66, 141, 255));
        loginRegisterJSeparator.setForeground(new java.awt.Color(66, 141, 255));
        loginRegisterJSeparator.setOpaque(true);
        loginRegisterJSeparator.setPreferredSize(new java.awt.Dimension(200, 2));

        passwordRegisterJPasswordField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        passwordRegisterJPasswordField.setText("Senha");
        passwordRegisterJPasswordField.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 5)));
        passwordRegisterJPasswordField.setEchoChar((char)0);
        passwordRegisterJPasswordField.setMargin(new java.awt.Insets(2, 2, 2, 2));
        passwordRegisterJPasswordField.setMinimumSize(new java.awt.Dimension(200, 24));
        passwordRegisterJPasswordField.setPreferredSize(new java.awt.Dimension(200, 24));
        passwordRegisterJPasswordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordRegisterJPasswordFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordRegisterJPasswordFieldFocusLost(evt);
            }
        });

        passwordRegisterJSeparator.setBackground(new java.awt.Color(66, 141, 255));
        passwordRegisterJSeparator.setForeground(new java.awt.Color(66, 141, 255));
        passwordRegisterJSeparator.setOpaque(true);
        passwordRegisterJSeparator.setPreferredSize(new java.awt.Dimension(200, 2));

        emailRegisterJTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        emailRegisterJTextField.setText("Email");
        emailRegisterJTextField.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 5)));
        emailRegisterJTextField.setMargin(new java.awt.Insets(2, 2, 2, 2));
        emailRegisterJTextField.setPreferredSize(new java.awt.Dimension(200, 24));
        emailRegisterJTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailRegisterJTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailRegisterJTextFieldFocusLost(evt);
            }
        });

        emailRegisterJSeparator.setBackground(new java.awt.Color(66, 141, 255));
        emailRegisterJSeparator.setForeground(new java.awt.Color(66, 141, 255));
        emailRegisterJSeparator.setOpaque(true);
        emailRegisterJSeparator.setPreferredSize(new java.awt.Dimension(200, 2));

        returnRegisterJButton.setBackground(new java.awt.Color(66, 141, 255));
        returnRegisterJButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        returnRegisterJButton.setForeground(new java.awt.Color(255, 255, 255));
        returnRegisterJButton.setText("Voltar");
        returnRegisterJButton.setFocusable(false);
        returnRegisterJButton.setPreferredSize(new java.awt.Dimension(90, 24));
        returnRegisterJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnRegisterJButtonActionPerformed(evt);
            }
        });

        newUserRegisterJButton.setBackground(new java.awt.Color(66, 141, 255));
        newUserRegisterJButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        newUserRegisterJButton.setForeground(new java.awt.Color(255, 255, 255));
        newUserRegisterJButton.setText("Salvar");
        newUserRegisterJButton.setFocusable(false);
        newUserRegisterJButton.setPreferredSize(new java.awt.Dimension(90, 24));
        newUserRegisterJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newUserRegisterJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout registerComponentsJPanelLayout = new javax.swing.GroupLayout(registerComponentsJPanel);
        registerComponentsJPanel.setLayout(registerComponentsJPanelLayout);
        registerComponentsJPanelLayout.setHorizontalGroup(
            registerComponentsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerComponentsJPanelLayout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addGroup(registerComponentsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(registerComponentsJPanelLayout.createSequentialGroup()
                        .addComponent(returnRegisterJButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(newUserRegisterJButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(emailRegisterJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailRegisterJSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameRegisterJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameRegisterJSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginRegisterJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginRegisterJSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordRegisterJSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordRegisterJPasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        registerComponentsJPanelLayout.setVerticalGroup(
            registerComponentsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerComponentsJPanelLayout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(nameRegisterJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameRegisterJSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(loginRegisterJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginRegisterJSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(passwordRegisterJPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordRegisterJSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(emailRegisterJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailRegisterJSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addGroup(registerComponentsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(returnRegisterJButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newUserRegisterJButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout registerJPanelLayout = new javax.swing.GroupLayout(registerJPanel);
        registerJPanel.setLayout(registerJPanelLayout);
        registerJPanelLayout.setHorizontalGroup(
            registerJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerJPanelLayout.createSequentialGroup()
                .addContainerGap(225, Short.MAX_VALUE)
                .addGroup(registerJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(headerComponentsJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(registerComponentsJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(225, Short.MAX_VALUE))
        );
        registerJPanelLayout.setVerticalGroup(
            registerJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerJPanelLayout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(headerComponentsJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(registerComponentsJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        cardLayoutJPanel.add(registerJPanel, "card2");

        loaderJPanel.setBackground(new java.awt.Color(255, 255, 255));
        loaderJPanel.setMinimumSize(new java.awt.Dimension(800, 470));
        loaderJPanel.setName(""); // NOI18N
        loaderJPanel.setPreferredSize(new java.awt.Dimension(800, 470));

        loadingIconJLabel.setFont(new java.awt.Font("Segoe UI Black", 1, 48)); // NOI18N
        loadingIconJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mapa/assets/loading_blue.gif"))); // NOI18N

        loadingTextJLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        loadingTextJLabel.setForeground(new java.awt.Color(66, 141, 255));
        loadingTextJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loadingTextJLabel.setText("Carregando...");

        javax.swing.GroupLayout loaderJPanelLayout = new javax.swing.GroupLayout(loaderJPanel);
        loaderJPanel.setLayout(loaderJPanelLayout);
        loaderJPanelLayout.setHorizontalGroup(
            loaderJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loaderJPanelLayout.createSequentialGroup()
                .addContainerGap(300, Short.MAX_VALUE)
                .addGroup(loaderJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(loadingIconJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(loadingTextJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(300, Short.MAX_VALUE))
        );
        loaderJPanelLayout.setVerticalGroup(
            loaderJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loaderJPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(loadingIconJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loadingTextJLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cardLayoutJPanel.add(loaderJPanel, "card3");

        loginSucessJPanel.setBackground(new java.awt.Color(255, 255, 255));
        loginSucessJPanel.setMinimumSize(new java.awt.Dimension(800, 470));
        loginSucessJPanel.setName(""); // NOI18N
        loginSucessJPanel.setPreferredSize(new java.awt.Dimension(800, 470));

        loginSucessbgJPanel.setBackground(new java.awt.Color(255, 255, 255));

        companyLogoSuccessIconJLabel.setFont(new java.awt.Font("Segoe UI Black", 1, 48)); // NOI18N
        companyLogoSuccessIconJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mapa/assets/logo.png"))); // NOI18N

        loginSuccessTextJLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        loginSuccessTextJLabel.setForeground(new java.awt.Color(0, 153, 0));
        loginSuccessTextJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginSuccessTextJLabel.setText("Acesso Autorizado!");

        returnSucessJButton.setBackground(new java.awt.Color(66, 141, 255));
        returnSucessJButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        returnSucessJButton.setForeground(new java.awt.Color(255, 255, 255));
        returnSucessJButton.setText("Voltar");
        returnSucessJButton.setFocusable(false);
        returnSucessJButton.setPreferredSize(new java.awt.Dimension(90, 24));
        returnSucessJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnSucessJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginSucessbgJPanelLayout = new javax.swing.GroupLayout(loginSucessbgJPanel);
        loginSucessbgJPanel.setLayout(loginSucessbgJPanelLayout);
        loginSucessbgJPanelLayout.setHorizontalGroup(
            loginSucessbgJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginSucessbgJPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(loginSuccessTextJLabel)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginSucessbgJPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(companyLogoSuccessIconJLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginSucessbgJPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(returnSucessJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        loginSucessbgJPanelLayout.setVerticalGroup(
            loginSucessbgJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginSucessbgJPanelLayout.createSequentialGroup()
                .addComponent(companyLogoSuccessIconJLabel)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(loginSuccessTextJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(returnSucessJButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout loginSucessJPanelLayout = new javax.swing.GroupLayout(loginSucessJPanel);
        loginSucessJPanel.setLayout(loginSucessJPanelLayout);
        loginSucessJPanelLayout.setHorizontalGroup(
            loginSucessJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginSucessJPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(loginSucessbgJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        loginSucessJPanelLayout.setVerticalGroup(
            loginSucessJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginSucessJPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(loginSucessbgJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cardLayoutJPanel.add(loginSucessJPanel, "card3");

        loginFailJPanel.setBackground(new java.awt.Color(255, 255, 255));
        loginFailJPanel.setMinimumSize(new java.awt.Dimension(800, 470));
        loginFailJPanel.setName(""); // NOI18N
        loginFailJPanel.setPreferredSize(new java.awt.Dimension(800, 470));

        loginFailbgJPanel.setBackground(new java.awt.Color(255, 255, 255));

        companyLogoFailIconJLabel.setFont(new java.awt.Font("Segoe UI Black", 1, 48)); // NOI18N
        companyLogoFailIconJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mapa/assets/logo.png"))); // NOI18N

        loginFailTextJLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        loginFailTextJLabel1.setForeground(new java.awt.Color(255, 0, 0));
        loginFailTextJLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginFailTextJLabel1.setText("Acesso Negado!");

        loginFailTextJLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        loginFailTextJLabel2.setForeground(new java.awt.Color(66, 141, 255));
        loginFailTextJLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginFailTextJLabel2.setText("Usuário e/ou senha inválidos!");

        loginFailTextJLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        loginFailTextJLabel3.setForeground(new java.awt.Color(66, 141, 255));
        loginFailTextJLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginFailTextJLabel3.setText("Tente novamente ou crie uma nova conta!");

        returnFailJButton.setBackground(new java.awt.Color(66, 141, 255));
        returnFailJButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        returnFailJButton.setForeground(new java.awt.Color(255, 255, 255));
        returnFailJButton.setText("Voltar");
        returnFailJButton.setFocusable(false);
        returnFailJButton.setPreferredSize(new java.awt.Dimension(90, 24));
        returnFailJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnFailJButtonActionPerformed(evt);
            }
        });

        newRegisterFailLoginButton.setBackground(new java.awt.Color(66, 141, 255));
        newRegisterFailLoginButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        newRegisterFailLoginButton.setForeground(new java.awt.Color(255, 255, 255));
        newRegisterFailLoginButton.setText("Criar Conta");
        newRegisterFailLoginButton.setFocusable(false);
        newRegisterFailLoginButton.setPreferredSize(new java.awt.Dimension(90, 24));
        newRegisterFailLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newRegisterFailLoginButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginFailbgJPanelLayout = new javax.swing.GroupLayout(loginFailbgJPanel);
        loginFailbgJPanel.setLayout(loginFailbgJPanelLayout);
        loginFailbgJPanelLayout.setHorizontalGroup(
            loginFailbgJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginFailbgJPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(loginFailbgJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(loginFailTextJLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(loginFailTextJLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(loginFailTextJLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginFailbgJPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(companyLogoFailIconJLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginFailbgJPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(returnFailJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(newRegisterFailLoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        loginFailbgJPanelLayout.setVerticalGroup(
            loginFailbgJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginFailbgJPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(companyLogoFailIconJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(loginFailTextJLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(loginFailTextJLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(loginFailTextJLabel3)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(loginFailbgJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(returnFailJButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newRegisterFailLoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout loginFailJPanelLayout = new javax.swing.GroupLayout(loginFailJPanel);
        loginFailJPanel.setLayout(loginFailJPanelLayout);
        loginFailJPanelLayout.setHorizontalGroup(
            loginFailJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginFailJPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(loginFailbgJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        loginFailJPanelLayout.setVerticalGroup(
            loginFailJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginFailJPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(loginFailbgJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cardLayoutJPanel.add(loginFailJPanel, "card3");

        registerSucessJPanel.setBackground(new java.awt.Color(255, 255, 255));
        registerSucessJPanel.setMinimumSize(new java.awt.Dimension(800, 470));
        registerSucessJPanel.setName(""); // NOI18N
        registerSucessJPanel.setPreferredSize(new java.awt.Dimension(800, 470));

        registerSucessbgJPanel.setBackground(new java.awt.Color(255, 255, 255));

        companyLogoSuccessIconJLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 48)); // NOI18N
        companyLogoSuccessIconJLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mapa/assets/logo.png"))); // NOI18N

        registerSucessTextJLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        registerSucessTextJLabel.setForeground(new java.awt.Color(0, 153, 0));
        registerSucessTextJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registerSucessTextJLabel.setText("Cadastro efetuado com sucesso!");

        returnRegSucessJButton1.setBackground(new java.awt.Color(66, 141, 255));
        returnRegSucessJButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        returnRegSucessJButton1.setForeground(new java.awt.Color(255, 255, 255));
        returnRegSucessJButton1.setText("Voltar");
        returnRegSucessJButton1.setFocusable(false);
        returnRegSucessJButton1.setPreferredSize(new java.awt.Dimension(90, 24));
        returnRegSucessJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnRegSucessJButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout registerSucessbgJPanelLayout = new javax.swing.GroupLayout(registerSucessbgJPanel);
        registerSucessbgJPanel.setLayout(registerSucessbgJPanelLayout);
        registerSucessbgJPanelLayout.setHorizontalGroup(
            registerSucessbgJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerSucessbgJPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(registerSucessTextJLabel)
                .addContainerGap())
            .addGroup(registerSucessbgJPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(companyLogoSuccessIconJLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(registerSucessbgJPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(returnRegSucessJButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        registerSucessbgJPanelLayout.setVerticalGroup(
            registerSucessbgJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerSucessbgJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(companyLogoSuccessIconJLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(registerSucessTextJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(returnRegSucessJButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout registerSucessJPanelLayout = new javax.swing.GroupLayout(registerSucessJPanel);
        registerSucessJPanel.setLayout(registerSucessJPanelLayout);
        registerSucessJPanelLayout.setHorizontalGroup(
            registerSucessJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerSucessJPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(registerSucessbgJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        registerSucessJPanelLayout.setVerticalGroup(
            registerSucessJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerSucessJPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(registerSucessbgJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cardLayoutJPanel.add(registerSucessJPanel, "card3");

        footerJLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        footerJLabel.setForeground(new java.awt.Color(93, 87, 107));
        footerJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        footerJLabel.setText("Marcos Almeida - github.com/MarcosGruah");

        javax.swing.GroupLayout backgroundJPanelLayout = new javax.swing.GroupLayout(backgroundJPanel);
        backgroundJPanel.setLayout(backgroundJPanelLayout);
        backgroundJPanelLayout.setHorizontalGroup(
            backgroundJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundJPanelLayout.createSequentialGroup()
                .addGroup(backgroundJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, backgroundJPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(footerJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(cardLayoutJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        backgroundJPanelLayout.setVerticalGroup(
            backgroundJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundJPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(cardLayoutJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(footerJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(backgroundJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(backgroundJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginJTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginJTextFieldFocusGained
        loginJTextField.setText("");
    }//GEN-LAST:event_loginJTextFieldFocusGained

    private void loginJTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginJTextFieldFocusLost
        if (loginJTextField.getText() == null || loginJTextField.getText().isEmpty()) {
            loginJTextField.setText("Login");

        }
    }//GEN-LAST:event_loginJTextFieldFocusLost

    private void nameRegisterJTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameRegisterJTextFieldFocusGained
        nameRegisterJTextField.setText("");
    }//GEN-LAST:event_nameRegisterJTextFieldFocusGained

    private void nameRegisterJTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameRegisterJTextFieldFocusLost
        if (nameRegisterJTextField.getText() == null || nameRegisterJTextField.getText().isEmpty()) {
            nameRegisterJTextField.setText("Nome");

        }
    }//GEN-LAST:event_nameRegisterJTextFieldFocusLost

    private void loginRegisterJTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginRegisterJTextFieldFocusGained
        loginRegisterJTextField.setText("");
    }//GEN-LAST:event_loginRegisterJTextFieldFocusGained

    private void loginRegisterJTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginRegisterJTextFieldFocusLost
        if (loginRegisterJTextField.getText() == null || loginRegisterJTextField.getText().isEmpty()) {
            loginRegisterJTextField.setText("Login");

        }
    }//GEN-LAST:event_loginRegisterJTextFieldFocusLost

    private void emailRegisterJTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailRegisterJTextFieldFocusGained
        emailRegisterJTextField.setText("");
    }//GEN-LAST:event_emailRegisterJTextFieldFocusGained

    private void emailRegisterJTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailRegisterJTextFieldFocusLost
        if (emailRegisterJTextField.getText() == null || emailRegisterJTextField.getText().isEmpty()) {
            emailRegisterJTextField.setText("Email");

        }
    }//GEN-LAST:event_emailRegisterJTextFieldFocusLost

    private void loginJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginJButtonActionPerformed

        String usernameInput = loginJTextField.getText().toLowerCase();
        String passwordInput = new String(passwordJPasswordField.getPassword());

        UserDao userDao = new UserDao();
        User userFound = userDao.findUserByLogin(usernameInput, passwordInput);

        if (userFound == null) {
            System.out.println("User not found.");
            loginJTextField.setText("Login");
            passwordJPasswordField.setText("Senha");
            passwordJPasswordField.setEchoChar('\u0000');
            loaderJPanel.setVisible(true);
            loginJPanel.setVisible(false);

            Timer timer = new Timer(1000, new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent arg0) {
                    loginFailJPanel.setVisible(true);
                    loaderJPanel.setVisible(false);

                }
            });
            timer.setRepeats(false); // Only execute once
            timer.start(); // Go go go!

        } else {
            System.out.println("User found.");
            loginJTextField.setText("Login");
            passwordJPasswordField.setText("Senha");
            passwordJPasswordField.setEchoChar('\u0000');
            loaderJPanel.setVisible(true);
            loginJPanel.setVisible(false);

            Timer timer = new Timer(1000, new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent arg0) {
                    loginSucessJPanel.setVisible(true);
                    loaderJPanel.setVisible(false);

                }
            });
            timer.setRepeats(false); // Only execute once
            timer.start(); // Go go go!
        }

    }//GEN-LAST:event_loginJButtonActionPerformed

    private void registerJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerJButtonActionPerformed

        loginJTextField.setText("Login");
        passwordJPasswordField.setText("Senha");
        passwordJPasswordField.setEchoChar('\u0000');

        registerJPanel.setVisible(true);
        loginJPanel.setVisible(false);
        this.requestFocus();

    }//GEN-LAST:event_registerJButtonActionPerformed

    private void returnRegisterJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnRegisterJButtonActionPerformed
        nameRegisterJTextField.setText("Nome");
        loginRegisterJTextField.setText("Login");
        passwordRegisterJPasswordField.setText("Senha");
        passwordRegisterJPasswordField.setEchoChar('\u0000');
        emailRegisterJTextField.setText("Email");

        loginJPanel.setVisible(true);
        registerJPanel.setVisible(false);
        this.requestFocus();
    }//GEN-LAST:event_returnRegisterJButtonActionPerformed

    private void newUserRegisterJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newUserRegisterJButtonActionPerformed

        User newUser = new User(
                nameRegisterJTextField.getText(),
                loginRegisterJTextField.getText().toLowerCase(),
                new String(passwordRegisterJPasswordField.getPassword()),
                emailRegisterJTextField.getText());

        UserDao userDao = new UserDao();
        userDao.addUser(newUser);

        nameRegisterJTextField.setText("Nome");
        loginRegisterJTextField.setText("Login");
        passwordRegisterJPasswordField.setText("Senha");
        passwordRegisterJPasswordField.setEchoChar('\u0000');
        emailRegisterJTextField.setText("Email");
        loaderJPanel.setVisible(true);
        registerJPanel.setVisible(false);

        Timer timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent arg0) {
                registerSucessJPanel.setVisible(true);
                loaderJPanel.setVisible(false);

            }
        });
        timer.setRepeats(false); // Only execute once
        timer.start(); // Go go go!

    }//GEN-LAST:event_newUserRegisterJButtonActionPerformed

    private void passwordJPasswordFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordJPasswordFieldFocusGained
        passwordJPasswordField.setText("");
        passwordJPasswordField.setEchoChar('\u2022');
    }//GEN-LAST:event_passwordJPasswordFieldFocusGained

    private void passwordJPasswordFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordJPasswordFieldFocusLost

        if (passwordJPasswordField.getPassword() == null || passwordJPasswordField.getPassword().length == 0) {
            passwordJPasswordField.setText("Senha");
            passwordJPasswordField.setEchoChar('\u0000');

        }
    }//GEN-LAST:event_passwordJPasswordFieldFocusLost

    private void passwordRegisterJPasswordFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordRegisterJPasswordFieldFocusGained
        passwordRegisterJPasswordField.setText("");
        passwordRegisterJPasswordField.setEchoChar('\u2022');
    }//GEN-LAST:event_passwordRegisterJPasswordFieldFocusGained

    private void passwordRegisterJPasswordFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordRegisterJPasswordFieldFocusLost
        if (passwordRegisterJPasswordField.getPassword() == null || passwordRegisterJPasswordField.getPassword().length == 0) {
            passwordRegisterJPasswordField.setText("Senha");
            passwordRegisterJPasswordField.setEchoChar('\u0000');

        }
    }//GEN-LAST:event_passwordRegisterJPasswordFieldFocusLost

    private void returnFailJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnFailJButtonActionPerformed
        loginJPanel.setVisible(true);
        loginFailJPanel.setVisible(false);
        this.requestFocus();

    }//GEN-LAST:event_returnFailJButtonActionPerformed

    private void newRegisterFailLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newRegisterFailLoginButtonActionPerformed
        passwordJPasswordField.setText("Senha");
        passwordJPasswordField.setEchoChar('\u0000');

        registerJPanel.setVisible(true);
        loginFailJPanel.setVisible(false);
        this.requestFocus();
    }//GEN-LAST:event_newRegisterFailLoginButtonActionPerformed

    private void returnSucessJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnSucessJButtonActionPerformed
        loginJPanel.setVisible(true);
        loginSucessJPanel.setVisible(false);
        this.requestFocus();
    }//GEN-LAST:event_returnSucessJButtonActionPerformed

    private void returnRegSucessJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnRegSucessJButton1ActionPerformed
        loginJPanel.setVisible(true);
        registerSucessJPanel.setVisible(false);
        this.requestFocus();
    }//GEN-LAST:event_returnRegSucessJButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundJPanel;
    private javax.swing.JPanel buttonComponentsPanel;
    private javax.swing.JPanel cardLayoutJPanel;
    private javax.swing.JLabel companyLogoFailIconJLabel;
    private javax.swing.JLabel companyLogoIconJLabel;
    private javax.swing.JLabel companyLogoSuccessIconJLabel;
    private javax.swing.JLabel companyLogoSuccessIconJLabel1;
    private javax.swing.JLabel companyNameJLabel;
    private javax.swing.JSeparator emailRegisterJSeparator;
    private javax.swing.JTextField emailRegisterJTextField;
    private javax.swing.JLabel footerJLabel;
    private javax.swing.JPanel headerComponentsJPanel;
    private javax.swing.JPanel loaderJPanel;
    private javax.swing.JLabel loadingIconJLabel;
    private javax.swing.JLabel loadingTextJLabel;
    private javax.swing.JPanel loginComponentsJPanel;
    private javax.swing.JPanel loginFailJPanel;
    private javax.swing.JLabel loginFailTextJLabel1;
    private javax.swing.JLabel loginFailTextJLabel2;
    private javax.swing.JLabel loginFailTextJLabel3;
    private javax.swing.JPanel loginFailbgJPanel;
    private javax.swing.JLabel loginIconJLabel;
    private javax.swing.JButton loginJButton;
    private javax.swing.JPanel loginJPanel;
    private javax.swing.JSeparator loginJSeparator;
    private javax.swing.JTextField loginJTextField;
    private javax.swing.JSeparator loginRegisterJSeparator;
    private javax.swing.JTextField loginRegisterJTextField;
    private javax.swing.JLabel loginSuccessTextJLabel;
    private javax.swing.JPanel loginSucessJPanel;
    private javax.swing.JPanel loginSucessbgJPanel;
    private javax.swing.JPanel logoComponentsJPanel;
    private javax.swing.JSeparator nameRegisterJSeparator;
    private javax.swing.JTextField nameRegisterJTextField;
    private javax.swing.JButton newRegisterFailLoginButton;
    private javax.swing.JButton newUserRegisterJButton;
    private javax.swing.JLabel passwordIconJLabel;
    private javax.swing.JPasswordField passwordJPasswordField;
    private javax.swing.JSeparator passwordJSeparator;
    private javax.swing.JPasswordField passwordRegisterJPasswordField;
    private javax.swing.JSeparator passwordRegisterJSeparator;
    private javax.swing.JPanel registerComponentsJPanel;
    private javax.swing.JButton registerJButton;
    private javax.swing.JPanel registerJPanel;
    private javax.swing.JPanel registerSucessJPanel;
    private javax.swing.JLabel registerSucessTextJLabel;
    private javax.swing.JPanel registerSucessbgJPanel;
    private javax.swing.JLabel registerTitleJLabel;
    private javax.swing.JButton returnFailJButton;
    private javax.swing.JButton returnRegSucessJButton1;
    private javax.swing.JButton returnRegisterJButton;
    private javax.swing.JButton returnSucessJButton;
    // End of variables declaration//GEN-END:variables
}
